dependabot.yml
package.json

Update cors, some clients had issues with DELETE

---

package.json
src/expressServer.ts
yarn.lock

The custom middleware didn't seem to be working with PATCH requests

Use cors package

---

.github/workflows/api-publish.yml

We can't automatically commit any more because of branch protection, so create a PR

Add workflow to do version bump PR

---

src/api.test.ts
src/api.ts
src/example.ts

We'll want the same kind of support in User (since that's where we ran
into this first!) as well, and a lot of tests.

Add support for discrimated models in GooseRestRouter

---

src/api.ts

If we use findOneAndUpdate, none of the middleware run. There's an
increased chance of API errors, but no chance of data loss, because
mongoose automatically versions documents and detects errors from
multiple writes over the same field without re-fetching the document.

Switch .patch to find then update

---

src/expressServer.ts

By the time addRoutes is called, middleware have already been applied.
Add a hook to let users configured middleware before all other middleware
(except Sentry).

Add option to set up middlewares early

---

src/api.test.ts
src/api.ts
src/example.ts
src/logger.ts

* Rename createdDeletedPlugin to createdUpdatedPlugin (misnamed).
* Fix up logger to log full messages

Fix up login to return JSON error, validate email/password correctly

---

jest.config.js
src/api.test.ts
src/api.ts
src/errors.ts
src/permissions.test.ts
src/transformers.test.ts

I'm starting to use the error messages in frontend, so having it
consistent is very helpful.

Use API Error everywhere

---

src/api.test.ts
src/api.ts

Make it to so create, read, update, and list operations all handle
populatePaths the same way.

Populate .post and .patch

---

src/expressServer.ts

* Capture fall through errors in Sentry
* Add Sentry user and request identification

Improve Sentry handling

---

src/api.ts

Export the async handler in api.ts

Export asyncHandler in api.ts

---

package.json
yarn.lock

Issue mentioned here: https://github.com/francescov1/mongoose-tsgen#type-instantiation-is-excessively-deep-and-possibly-infinite

Downgrade mongoose to fix compilation issues regarding type instantiation

---

src/auth.test.ts
src/auth.ts
src/passport.ts
src/tests.ts

Also add a test around locking out a user account after failures.

Break up login attempts and rate limiting

---

src/api.ts
src/tests.ts

With strict mode set on a model, Mongoose will throw an error because the special query params aren't on the model.

Fix bug when using page/limit with a strict model

---

src/api.test.ts
src/auth.test.ts
src/auth.ts
src/example.ts
src/expressServer.ts
src/permissions.test.ts
src/transformers.test.ts

Split up setting up auth handling and all the auth routes so we can insert the logging middleware in the middle.

Fix user ids not printing in logs

---

src/api.test.ts
src/api.ts

Populate paths can either be a single string that works for everyone, or a function that inspects the request and returns a list of paths to populate. This allows for migrations and backwards compatibility around population.

Allow function for populatePaths

---

src/errors.ts

For disabling external error tracking like Sentry. Tracking is on by default.

Add flag for disabling external error tracking

---

src/api.ts

`model.name` did not seem to be correctly grabbing the string name for the model in the api. Changed it to `model.modelName` according to the mongoose api definition

Update model name in logging

---

src/api.ts

Ran into some confusing errors when these weren't caught.

Catch responseHandler errors

---

src/api.ts

Reverts FlourishHealth/ferns-api#297

Revert "Catch responseHandler errors"

---

src/expressServer.ts
src/logger.ts

Reverts FlourishHealth/ferns-api#296

Revert "Add flags for logging slow requests"

---

src/__snapshots__/openApi.test.ts.snap
src/api.ts
src/auth.test.ts
src/auth.ts
src/expressServer.ts
src/plugins.ts
src/tests.ts

Also store some extra info on the JWT token to close a TODO.

Allow disabling users

---

src/errors.ts

enhancement
___
- Enhanced `APIError` to append the error stack to the error message if an error object is provided. This aims to improve error diagnostics in Sentry by providing more detailed error information.
___
<tr>
<td>
<details>
<summary><strong>errors.ts</strong><dd><code>Enhance APIError Logging with Error Stack Details</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/errors.ts
<li>Enhanced the <code>APIError</code> constructor to include error stack in the <br>message if available.<br> <li> Maintained existing error information while appending the error stack <br>for more detailed logging.<br>
</details> …

Add more error detail for Sentry

---

src/expressServer.ts

enhancement
___
- Added the ability to configure the Sentry environment through an environment variable (`SENTRY_ENVIRONMENT`). Defaults to "production" if not set.
___
<tr>
<td>
<details>
<summary><strong>expressServer.ts</strong><dd><code>Add Sentry Environment Configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/expressServer.ts
<li>Added <code>environment</code> configuration to Sentry initialization, defaulting <br>to "production" if <code>SENTRY_ENVIRONMENT</code> is not set.<br>
</details>
</td>
<td><a …

Allow setting sentry environment

---

src/auth.ts

enhancement
___
- Enhanced logging around token refresh scenarios in `src/auth.ts` to improve traceability and debugging capabilities.
- Added user ID to log messages for better identification of issues related to token operations.
___
<tr>
<td>
<details>
<summary><strong>auth.ts</strong><dd><code>Enhance Logging for Token Refresh Scenarios</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/auth.ts
<li>Added detailed logging for various token refresh scenarios including <br>missing refresh token, missing REFRESH_TOKEN_SECRET, token refresh <br>errors, and successful token …

Add logging around tokens

---

src/api.test.ts
src/api.ts

Otherwise we are silently discarding data.
___
enhancement
___
- Added Sentry integration to log and capture messages when querying over the limit without pagination.
- Enhanced API tests to mock Sentry methods and verify the new behavior.
- This ensures that data truncation issues are logged and monitored, improving the reliability and observability of the API.
___
<tr>
<td>
<details>
<summary><strong>api.test.ts</strong><dd><code>Enhance API Tests with Sentry Integration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/api.test.ts
<li>Imported …

Capture Sentry message when querying over limit without page

---

src/openApi.ts

enhancement
___
- Introduced a new middleware function `readOpenApiMiddleware` in `src/openApi.ts` to handle generic read operations.
- This function supports dynamic properties and query parameters, enhancing flexibility for endpoints not directly tied to a model.
- Includes error handling for missing OpenAPI configurations and merges user-defined settings with default responses.
___
<tr>
<td>
<details>
<summary><strong>openApi.ts</strong><dd><code>Implement Generic Read OpenAPI Middleware</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/openApi.ts
<li>Added a …

Add generic readOpenApiMiddleware

---

src/auth.test.ts
src/auth.ts

We weren't throwing an error if the token could not be decoded or was expired, so it just hung. This now throws an error.
___
Bug fix, Tests
___
- Added a new test to verify that tokens expire correctly and return a 401 status.
- Introduced the use of fake timers in tests to simulate the passage of time.
- Ensured timers are cleaned up after each test to avoid side effects.
- Updated JWT verification logic to return a 401 status with an error message if the token cannot be decoded or has expired.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests
<tr>
<td>
<details>
<summary><strong>auth.test.ts</strong><dd><code>Add tests for token expiration and timer handling.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

Return error if jwt cannot be decoded properly or has an error

---

src/auth.test.ts
src/auth.ts
src/expressServer.ts

Enhancement, Tests
___
- Implemented customizable token expiration logic in the `generateTokens` function.
- Added expiration checks in token verification to ensure tokens are not used past their expiration.
- Extended `AuthOptions` to include `generateTokenExpiration` and `generateRefreshTokenExpiration` functions.
- Added tests to verify token expiration behavior and integrated fake timers setup and teardown in tests.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests
<tr>
<td>
<details>
<summary><strong>auth.test.ts</strong><dd><code>Add tests for token expiration and fake timers setup.</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/auth.test.ts
<li>Added fake timers setup and teardown in …

Customizable token expirations and check for token expirations

---

.vscode/settings.json
package.json
src/__snapshots__/openApi.test.ts.snap
src/expressServer.ts
src/openApi.test.ts
yarn.lock

Probably one more PR to come, but this brings us in the right direction and fixes swagger ui.
___
Enhancement, Tests, Dependencies
___
- Updated OpenAPI middleware usage and fixed Swagger UI initialization in `src/expressServer.ts`.
- Added a new custom OpenAPI middleware for the `food/count` endpoint and corresponding test in `src/openApi.test.ts`.
- Changed VSCode settings for ESLint and import organization to "explicit" in `.vscode/settings.json`.
- Upgraded `@wesleytodd/openapi` to version 1.1.0 and updated several other dependencies in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>expressServer.ts</strong><dd><code>Update OpenAPI …

Upgrade open api generator and test with custom

---

src/expressServer.ts

We'll use this to e.g. add more `ignoreErrors` options.

Allow setting Sentry options in expressServer

---

src/auth.ts

enhancement
___
- Removed session management from the authentication middleware to streamline the authentication process.
- Disabled storing failure messages in sessions to prevent unnecessary session usage.
- Eliminated the need for user model serialization and deserialization, simplifying the setupAuth function.
- Updated the local strategy authentication to not use sessions, aligning with the new stateless approach.
___
<tr>
<td>
<details>
<summary><strong>auth.ts</strong><dd><code>Remove session management from authentication flow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/auth.ts
<li>Removed session management …

Remove use of sessions

---

src/__snapshots__/openApi.test.ts.snap
src/api.test.ts
src/openApi.test.ts
src/openApi.ts

Enhancement
___
- Support direct number queries in API endpoints
- Update OpenAPI schema for number field queries
- Add test coverage for number query functionality
___
```mermaid
flowchart LR
A["API Request"] --> B["Number Query Parser"]
B --> C["Direct Number Value"]
B --> D["Range Operators ($gt, $gte, etc.)"]
C --> E["Query Execution"]
D --> E
E --> F["Response"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>api.test.ts</strong><dd><code>Add number query test case</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

Support querying for a number directly
