src/api.ts
Instead of having to calculate dates on the front end, supporting passing in a 'period' param. The logic will be in 'queryFilter' on the backend but we can't have the period passing through as a part of the query to the schema since it isn't actually in the schema.
=> Support 'period' query filter

src/index.ts
When moving code around, I forgot to add plugins to index.ts so they'd be
exported outside the package.
=> Export plugins

package.json, src/plugins.test.ts, src/plugins.ts, yarn.lock
.findOne should generally be considered unsafe, unless using a unique
index, but that's not very apparent from the docs. Replacing all usages
of .findOne with .findOneOrThrows should prevent inadvertant and silent
issues while maintaining a good dev experience, rather than writing a
similar if/else if/else statement every time you want to find one doc.
=> Add findOneOrThrows plugin

src/api.ts
It's a little weird when we read a single object and it's not populated, whereas it is when you list the same item.
=> Populate object reads like we populate list queries

src/api.test.ts, src/auth.ts, src/plugins.ts
The token plugin wasn't setting "select: false" to default Mongoose to
not selecting that field. If the plugin was used on users and then you
return the result of `User.find()`, the tokens would be readable. This
follows the same pattern passport uses with hash and salt fields.
=> Fix potential JWT token leak

src/errors.ts
By default, it is only capturing 5xx errors, which aren't as common as all the APIErrors which tend to be 4xx.
=> Capture more errors with Sentry

src/api.test.ts, src/auth.test.ts, src/auth.ts, src/passport.ts, src/tests.ts
The previous PR didn't fix case insensitive emails because the email login strategy searched for the email directly instead of using passports `findByUsername()`, where the insensitive search was added. Also escape the regex created for case insensitivity, because plus symbols caused errors.
=> Make email logins case insensitive

src/api.ts
This one needs to be passed into options.queryFilter, so if we never add it to query, queryFilters looking for "period" break.
=> Fix broken period query param

jest.config.js, src/api.test.ts, src/auth.test.ts, src/auth.ts, src/expressServer.ts, src/tests.ts, src/tests/index.ts, src/tests/jestSetup.ts, tsconfig.json
The `/auth/signup` endpoint is completely unauthenticated and sometimes there is a requirement to not allow external entities to sign up for an app. This will allow us to turn off this endpoint and only allow sign up done by an already authenticated user (Like an admin creating a user account on their behalf).
To avoid making this a breaking change, it'll default to enabled.
=> Ability to disable signup endpoint and fix up tests

package.json, src/errors.ts, src/expressServer.ts, yarn.lock
We were relying on the implementor of this library to call `setupErrorLogging`, but it should be done within the `setupServer` function so we can pass in `app` for tracing.
Also, we were doubly grabbing errors since Sentry already got them via their Error handler and we were grabbing them again with our middleware.
Also add profiling.
=> Update Sentry to set up within the setupServer function

src/auth.ts, src/expressServer.ts, src/logger.ts
Logging full JS objects becomes quite problematic, especially when using things like Google's StackDriver.
This is a breaking change, since all logging that passes multiple args won't compile. We're also changing what's exported as `logger` from a full winston logger to a wrapper with a few methods exposed. If you need to update the winston logger, that is exported as `winstonLogger` now.
=> Enforce only a single string when Logging

yarn.lock
In versions <=8.5.1 of jsonwebtoken library, lack of algorithm definition and a falsy secret or key in the jwt.verify() function can lead to signature validation bypass due to defaulting to the none algorithm for signature verification.
=> Upgrade passport-jwt to fix jwt vulnerability

yarn.lock
qs before version 6.9.7 is vulnerable to Prototype Pollution
=> Update supertest to move qs to a nonvulnerable version

src/auth.ts, src/errors.ts, src/expressServer.ts
Right now when we hit an API that is unauthorized (like jwt expired) it just sends 'Unauthorized' in the body which causes parsing issues since its not valid json. This makes sure even our 401's are formatted as an 'APIError' so it's valid json.
=> APIError for Unauthorized

package.json, src/api.test.ts, src/api.ts, src/plugins.ts, yarn.lock
Also upgrade passport-local-mongoose to handle Mongoose v7 and typescript to match other repos.
Fix tests around discriminators which changed in v7.
=> Upgrade Mongoose to v7

src/errors.ts
- Avoids logging errors
- Avoids the fallthru error handler since it sends the response as soon as it sees the 401
- Sends APIErrors without triggering fallthru
=> Send Unauthorized without triggering fallthru error handler

src/errors.ts
Trying to track down this error, but we aren't getting enough details: https://flourish-health.sentry.io/issues/4115782684/?query=is%3Aunresolved&referrer=issue-stream&stream_index=10
=> Include details in when APIrror is printed

.github/workflows/api-ci.yml, .github/workflows/api-publish.yml
We were getting warnings about node-setup@v1 being deprecated because it uses Node 12.
While we're at it:
Node 14 is in maintence, 16 is only active for another few months, 18 is active, 20 is in testing.
=> Remove deprecated node-setup, use Node 18/20, Mongo 6.0

package.json, src/__snapshots__/openApi.test.ts.snap, src/api.test.ts, src/api.ts, src/errors.ts, src/example.ts, src/expressServer.ts, src/openApi.test.ts, src/openApi.ts, src/plugins.ts, yarn.lock
When using expressServer, it will automatically configure a /swagger route to explore the API.
Update APIError to more closely match JSONAPI's error doc (which it is based on).
Update example so it's more usable for testing.
Breaking change: changes the call signature for `addRoutes` to allow passing the openApi 
in `options`. Also, passing the `options` may let downstream `addRoutes` be smarter,
so win-win.
=> Add OpenAPI specifications for FernsRouter

src/__snapshots__/openApi.test.ts.snap, src/api.ts, src/openApi.test.ts, src/openApi.ts
For APIs with populatePaths set to an array of strings, use those strings to try and guess at the model being populated and add it to the OpenAPI schema. Otherwise the schema would say it was returning a string (for the ObjectID) but really return the whole API, messing up SDKs.
Doesn't currently support the function version of populate paths.
=> Handle population in OpenAPI

src/auth.ts
Switching user models to have more required fields (like name) means registring with only email and password will fail with mongoose.
=> Update the way registration works

src/__snapshots__/openApi.test.ts.snap, src/api.test.ts, src/api.ts, src/errors.ts, src/openApi.test.ts, src/openApi.ts, src/tests.ts, src/transformers.ts
Deprecate postList/postGet, responseHandler should manage these. transformers will be removed in a release soon.
Pass error into API error so we can show stack traces. I ran into issues tracking down what function was throwing because we were swallowing the stack trace.
Allow setting extra values via OpenAPI with openApiExtraModelProperties. This is helpful if you add values to objects in the responseHandler so the SDK generates properly and with types.
=> Add responseHandler, deprecate postList/postGet

src/api.ts
RTK Query throws an error when we return an empty response.
=> Return JSON for delete endpoints

src/expressServer.ts
In an effort to make our services more observable, sometimes we want to get rid of a lot of the console logging in production and just focus on things like Google Cloud Logging.
=> Make request logging optional

src/logger.ts
This exists but wasn't in the types, causing issues.
=> Add logRequests param

src/expressServer.ts
We keep hitting our quota for performance monitoring, and it is one endpoint causing the issue. This will allow us to ignore the endpoint in question by passing in an optional configuration parameter of `ignoreTraces`.
=> Support ignoring trace paths for Sentry

package.json, src/auth.ts, src/openApi.ts, src/plugins.test.ts, src/plugins.ts, src/tests.ts, yarn.lock
I noticed this pattern a few times in my code and code review where we expect exactly one item to match. Add a plugin to clean up that code. Also allow setting the error params for both plugins so we can customize statuses and error messages.
Also export some more stuff for OpenAPI (had this hanging around on my branch, whoops).
=> Add findExactlyOne plugin, allow custom findOneOrThrow errors

src/openApi.ts
This allows us to send $in queries from clients.
=> Add $in query to openapi param definition

src/expressServer.ts, types.d.ts
Slack changed the way you use webhooks and it is a 1-1 relationship webhook-channel now. So this way, we can pass in a basic object as the env variable to still support multiple channels.
=> Updates to sendToSlack

src/__snapshots__/openApi.test.ts.snap, src/api.test.ts, src/api.ts, src/tests.ts
This allows updating a single field in a nested document instead of needing to rewrite the entire doc.
=> Allow dot notation updates

src/auth.ts
This can happen for various reasons. One example is during tests or staging data generation, users may get deleted. When they try to refresh, the whole server would crash.
=> Fix crash with undefined user on token refresh

src/expressServer.ts
We were getting warnings about use of a deprecated method of setting the tag, so fixed it with the new way of doing it.
=> Fix use of deprecated Sentry scope tag

package.json, yarn.lock
enhancement
___
- Upgraded `mongoose` to version `8.2.2` in `devDependencies` to leverage new features and improvements.
- Updated `mongoose` version requirement in `peerDependencies` to `^8.0.0` to ensure compatibility with the latest version.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Upgrade Mongoose to Version 8</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<li>Upgraded <code>mongoose</code> version from <code>7.6.2</code> to …
=> Upgrade mongoose to v8

src/api.ts
TS suggested isInitialized was a real function, but that doesn't appear to be true.
___
bug_fix
___
- Wrapped the Sentry message capturing in a try-catch block to prevent unhandled errors.
- Added error logging within the catch block to ensure visibility of any issues during Sentry operations.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Error handling</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>api.ts</strong><dd><code>Improved Error Handling for Sentry Message Capturing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/api.ts
<li>Wrapped <code>Sentry.captureMessage</code> in a try-catch block to handle potential <br>errors.<br> <li> Added logging for errors caught when attempting to capture a …
=> Fix Sentry limit logger

src/__snapshots__/openApi.test.ts.snap, src/openApi.ts
Cuts the OpenAPI.json almost in half. Note the snapshot changes for how much this fixes it...
___
enhancement
___
- Introduced a reusable component for the API error schema to reduce redundancy and improve maintainability.
- Created a new function `createAPIErrorComponent` that encapsulates the detailed API error schema, making it easier to manage and update.
- Updated the `apiErrorContent` to reference the newly created APIError component, streamlining the OpenAPI.json structure.
- Integrated the creation of the APIError component into the OpenAPI middleware setup, ensuring it is available application-wide.
___
<tr>
<td>
<details> …
=> Use component to shrink OpenAPI.json

src/expressServer.ts
Prevent silent failures when url not found
___
Bug fix, Enhancement
___
- Improved the `sendToSlack` function to use the "default" channel if the provided channel is not found.
- Added error capturing with Sentry when no webhook URL is set for the specified or default channel.
- Enhanced error handling by capturing exceptions when posting to Slack fails.
___
<tr>
<td>
<details>
<summary><strong>expressServer.ts</strong><dd><code>Improve error handling and fallback logic in `sendToSlack` function</code></dd></summary>
<hr>
src/expressServer.ts
<li>Added fallback to "default" channel if provided channel is not found.<br> <li> Added error capturing with …
=> update send to slack function

package.json, yarn.lock
dependencies
___
- Upgraded `expo-server-sdk` dependency from version 3.6.0 to 3.10.0 in `package.json`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Upgrade `expo-server-sdk` dependency to version 3.10.0</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<li>Upgraded <code>expo-server-sdk</code> dependency from version 3.6.0 to 3.10.0.<br>
</details>
</td>
<td><a href="https://github.com/FlourishHealth/ferns-api/pull/411/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>
___
> 💡 **PR-Agent …
=> Upgrade expo-server-sdk

package.json, src/expressServer.ts, src/plugins.test.ts, src/plugins.ts, yarn.lock
Add a type that forces dates to end in 00:00:00.000Z UTC to match ferns-ui handling of date only fields.
Also remove the verbose but not very useful startup logging. It didn't include any of the FernsRouter routes and gets chatty with microservices and tests.
___
enhancement, tests, dependencies
___
- Introduced a new `DateOnly` schema type that normalizes dates to `00:00:00.000Z` using Luxon.
- Added tests for the `DateOnly` schema type to ensure proper date adjustment and error handling.
- Removed verbose startup logging from the express server to reduce noise.
- Updated `package.json` to include the `luxon` dependency for date handling.
___
<tr>
<td> …
=> Add DateOnly schema type

src/plugins.test.ts, src/plugins.ts
Queries like $gte didn't work because they weren't being cast correctly.
___
enhancement, tests
___
- Enhanced the `DateOnly` schema type to support query operators like $gte, $lte by implementing conditional handlers and casting logic.
- Improved error message in `auth.ts` for token refresh failures to provide more context.
- Added a test case in `plugins.test.ts` to verify filtering functionality on `DateOnly` fields using date range queries.
___
<tr>
<td>
<details>
<summary><strong>auth.ts</strong><dd><code>Enhance error message for token refresh failures</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> Fix up querying for DateOnly field

src/auth.test.ts, src/auth.ts, src/expressServer.ts
Tracking down some weird auth issues. Move the /login, /signup, and /refresh_token routes outside of the JWT middleware. In a couple cases it was intercepting and giving a 401 before /refresh_token got a chance to do anything, and I've seen odd issues with /login getting 401s.
Add more logging to hopefully help track these issues in the future.
___
enhancement, bug fix
___
- Enhanced JWT error logging by including user details and error specifics.
- Moved `/login`, `/signup`, and `/refresh_token` routes outside of JWT middleware to prevent premature 401 errors.
- Added `addMeRoutes` function to handle `/me` endpoint separately.
- Reordered middleware initialization to ensure auth routes are processed before JWT middleware.
___
<table><thead><tr><th></th><th align="left">Relevant …
=> Auth changes and logging

src/auth.ts
enhancement
___
- Added functionality to allow requests with a "Secret" prefix in the authorization header to bypass JWT decoding.
- This change enables handling of non-JWT authorization tokens more effectively.
___
<tr>
<td>
<details>
<summary><strong>auth.ts</strong><dd><code>Support "Secret" prefix in authorization headers</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/auth.ts
<li>Added support for "Secret" prefix in authorization headers.<br> <li> Bypasses JWT decoding for requests with "Secret" prefix.<br>
</details>
</td>
<td><a href="https://github.com/FlourishHealth/ferns-api/pull/456/files#diff-84a5d1 …
=> Allow Authorization Secret in headers

src/expressServer.ts
Also changed the optional stuff to an object so it is easy to add/remove from in the future. It'll be a breaking change, but easy to find/replace.
enhancement
___
- Enhanced the `sendToSlack` function to include an optional `env` parameter.
- Prefixed Slack messages with the environment name when the `env` parameter is provided.
- Updated the function signature to accept parameters as an options object, improving flexibility.
___
<tr>
<td>
<details>
<summary><strong>expressServer.ts</strong><dd><code>Add environment preface option to Slack messages</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> Add env preface option to sendToSlack

src/expressServer.ts, src/index.ts, src/openApi.test.ts, src/openApiEtag.ts
This file winds up getting fetched a lot. It's a big file that doesn't change all that often. Use ETags to allow the client to use a cached version.
To test, build it, copy it into flourish backend's node_modules, start the backend, and log in with the app. Observe the first time you get a 200 and download openapi.json. When refreshing you get a 304 and don't download the file.
___
Enhancement
___
- Add ETag middleware for OpenAPI JSON endpoint caching
- Implement conditional requests with If-None-Match header support
- Generate SHA256-based ETags for response validation
- Add comprehensive test coverage for ETag functionality
___
```mermaid
flowchart LR
A["Client Request"] --> B["ETag Middleware"]
B --> C["Check If-None-Match"]
C --> D["ETag Match?"]
D -->|Yes| E["Return 304"]
D -->|No| …
```
=> Add OpenAPI ETag
